name: github-action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 新建一个名为checkout_actions的步骤
      - name: checkout_actions
        #使用checkout@v2这个action获取源码
        uses: actions/checkout@v2 
      # 使用建一个名为setup-node的步骤
      - name: setup-node
        # 使用setup-node@v1这个action
        uses: actions/setup-node@v1
        # 指定某个action 可能需要输入的参数
        with:
          node-version: '16'
      # 安装依赖命令
      - name: npm install
        run: yarn install
      # 执行打包命令 yarn rollup -c
      - name: build
        run: yarn rollup -c